<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://ws.cdyne.com/WeatherWS/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://ws.cdyne.com/WeatherWS/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="tempo">
        <plnk:role name="WeatherSoap">
            <plnk:portType name="tns:WeatherSoap"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://ws.cdyne.com/WeatherWS/" location="http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL"/>
</wsdl:definitions>
